project:
  type: book
filters:
   - include-code-files

book:
  title: "Forecasting Solar Induced Fluorescence for German Forest after the Heatwave in 2018 using Deep Learning"
  author: "Luis Maecker, Imke Ott, Moritz Mischi"
  date: "26.07.2024"
  chapters:
    - index.qmd
    - quarto_book/intro.qmd
    - main_copy.ipynb
    - part: "Function scripts"
      chapters:
        - quarto_book/config.qmd
        - quarto_book/utils.qmd
        - quarto_book/modelling_functions.qmd
    - part: "Executable scripts"
      chapters:
        - quarto_book/01_load_aux_data.qmd
        - quarto_book/02_cube_preprocessing.qmd
        - quarto_book/03_base_analysis.qmd
        - quarto_book/04_test_modelling.qmd
        - quarto_book/05_modelling.qmd
    - quarto_book/references.qmd

bibliography: quarto_book/references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    toc: true
    toc-depth: 4
    code-overflow: scroll 
    highlight-style: gruvbox

conda:
  environment: sif_env3


