project:
  type: book
filters:
   - include-code-files

book:
  navbar:
    collapse: false
  title: "Forecasting Solar Induced Fluorescence for German Forest after the Heatwave in 2018 using Deep Learning"
  author: "Luis Maecker, Imke Ott, Moritz Mischi"
  date: "26.07.2024"
  chapters:
    - index.qmd
    - quarto_files/intro.qmd
    - main_workflow.ipynb
    - part: "Executable scripts"
      chapters:
        - quarto_files/01_load_aux_data.qmd
        - quarto_files/02_cube_preprocessing.qmd
        - quarto_files/03_base_analysis.qmd
        - quarto_files/04_test_modelling.qmd
        - quarto_files/05_modelling.qmd
    - part: "Function scripts"
      chapters:
        - quarto_files/config.qmd
        - quarto_files/utils.qmd
        - quarto_files/modelling_functions.qmd
    - quarto_files/DMP.qmd
    - quarto_files/references.qmd

bibliography: quarto_files/references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    toc: true
    toc-depth: 4
    code-overflow: scroll 
    highlight-style: gruvbox



conda:
  environment: sif_env3
