name: sif_env_test
channels:
  - conda-forge
  - defaults
dependencies:
  - python = 3.11
  - pip
  - numpy
  - pandas
  - geopandas
  - matplotlib
  - xcube
  - rasterio
  - xarray
  - rioxarray
  - tensorflow
  - keras
  - ipykernel
  - pip:
    - ee
    - geemap
    - scikeras
