# Outline {.unnumbered}

This is the quarto book for the project **"Forecasting Solar Induced Fluorescence for German Forest after the Heatwave in 2018 using Deep Learning"**. 
This project was created as part of two course projects in the "Earth System Data Science and Remote Sensing" Master at Leipzig University. The courses are *Scientific Writing* by [Prof. Dr. Miguel Mahecha](https://www.uni-leipzig.de/personenprofil/mitarbeiter/prof-dr-miguel-mahecha) and *Spatio-temporal Data* by [Dr. Guido Kraemer](https://www.uni-leipzig.de/personenprofil/mitarbeiter/dr-guido-kraemer). This quarto book contains all code used for the analysis, shows the main results and briefly discusses them, as well as a Data Management Plan. The project is fully reproducible and all data is openly available. The project can be found at this [Gitlab repository](https://git.sc.uni-leipzig.de/ss2024-12-geo-m-ds02/sif-prediction).

## Structure

## Authors

Luis Maecker - maecker@studserv.uni-leipzig.de

Imke Ott - imke.ott@studserv.uni-leipzig.de

Moritz Mischi - moritz.mischi@studserv.uni-leipzig.de

