---
author: "Luis Maecker, Mortiz Mischi, Imke Ott"
date: "2024-07-28"
output:
  pdf_document:
    includes:
      in_header: |
        \usepackage{fancyhdr}
        \pagestyle{plain}
        \fancyhf{}
        \renewcommand{\headrulewidth}{0pt}
        \renewcommand{\footrulewidth}{0pt}
        \pagestyle{plain}
        \thispagestyle{empty}
---

<div style="text-align: center; margin-top: 200px;">

<span style="font-size: 1.2em; font-weight: bold;">Project Number:</span> SS2024 12-GEO-M-DS02 <br><br>

<span style="font-size: 1.2em; font-weight: bold;">Project Acronym:</span> LSTM-SIF <br><br>

<span style="font-size: 1.2em; font-weight: bold;">Project title:</span> Forecasting Solar Induced Fluorescence for German Forest after the Heatwave in 2018 using Deep Learning <br><br><br><br>

<span style="font-size: 2.5em; font-weight: bold;">DATA MANAGEMENT PLAN</span>

</div>

\newpage

## Data Summary

The objective of the data collection in this project is purely educational, serving as an exercise within the master’s course of 'Spatio-temporal Data' (course ID: **SS2024 12-GEO-M-DS02**) offered under the 'Earth System Data Science and Remote Sensing' masters-program at the University of Leipzig. The project collects its auxiliary data from the Food and Agriculture Organization (FAO) & the **CORINE Land Cover 2000** (CLC2000) product by Copernicus. Using ERA5 climate data, the project aims to forecast sun-induced chlorophyll for German forests using an LSTM model.

## FAIR Data

### Findable

#### Climate Data for the analysis

- The forecasting task is completed by training a model on **ERA5 climate data**, which is accessible within the Earth System Data Cube, provided by the [Earth System Data Lab](http://www.earthsystemdatalab.net/). Link to the data: [Earth System Data Cube](http://data.rsc4earth.de/EarthSystemDataCube/v3.0.1/esdc-8d-0.25deg-256x128x128-3.0.1.zarr/). The original ERA-5 data was created by Hersbach et al [@Hersbach2020].

#### Sun Induced Fluoreseence Data
- The Sun induced fluoresence data for this project was created by Xing Li and Jingfeng Xiao [@Li2019]. It is also accessible throught the Earhy System Data Lab. T

#### Auxiliary data

- German border shapefile
    - In this project, the **GAUL 2015 Level 0** dataset from the Food and Agriculture Organization ([FAO, 2015](https://data.apps.fao.org/?lang=en)) is used to get the administrative unit of Germany as a shapefile.
- Forest cover
    - **CORINE Land Cover 2000 (CLC2000)** acquired by Landsat-7 ETM, was used to extract forest pixels. The full dataset can be found [here](https://doi.org/10.2909/ddacbd5e-068f-4e52-a596-d606e8de7f40).

### Accessible

All data used in this project is free of charge and openly accessible (through the links provided).

- The GAUL data is freely accessible through the FAO's [Geospatial Data platform](https://data.apps.fao.org/map/catalog/srv/ger/catalog.search#/metadata/9c35ba10-5649-41c8-bdfc-eb78e9e65654), ensuring that users can easily download and use the data for various applications.
- The CLC programme is a part of the Copernicus Land Monitoring Service ([Copernicus](https://land.copernicus.eu/)) run by the European Commission and the European Environment Agency. Access to this data is based on a principle of full, open, and free access as established by the Copernicus data and information policy Regulation (EU) No 1159/2013 of 12 July 2013. This regulation establishes registration and licensing conditions for GMES/Copernicus users.
- ERA5 data can be accessed through the Climate Data Store (CDS) managed by the Copernicus Climate Change Service (C3S). Users can freely access a comprehensive range of meteorological data in this [catalog](https://cds.climate.copernicus.eu/cdsapp#!/search?type=dataset&text=). For the project all data was accessible through the Earth System Data Cube.

### Interoperable

- **Standardized Data Formats**
    - The utilized data is stored in standard formats such as .nc, .tif, and .shp, each documented with metadata.
- **Data Generation with Python**
    - The generation of new data employed the freely available programming language Python and its open-source libraries.
- **Study Area Mask Standardization**
    - The study area mask was created in the standard .shp format, ensuring reproducibility with the freely available software QGIS.

### Re-use

#### Licenses

- The FAO GAUL 2015 Level 0 data is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 3.0 IGO ([CC BY-NC-SA 3.0 IGO](https://data.apps.fao.org/catalog/dataset/global-administrative-unit-layers-gaul-2015)) license. This means one is free to share and adapt the data, provided one gives appropriate credit. It is not meant for commercial purposes.
- The CLC2000 dataset is licensed under the Creative Commons Attribution 4.0 International ([CC BY 4.0](https://land.copernicus.eu/api/en/products/corine-land-cover/clc-2000)) license.
- The ERA5 dataset used in the Earth System Data Cube is licensed under the [Creative Commons Attribution 4.0 International](https://www.ecmwf.int/en/forecasts/dataset/ecmwf-reanalysis-v5) (CC BY 4.0).

#### Data Quality Assurance

- **ERA5**: Detailed documentation and validation reports are available, providing insights into the QA measures taken to ensure data quality ([ERA5 Documentation](https://www.ecmwf.int/en/forecasts/dataset/ecmwf-reanalysis-v5)).
- **FAO GAUL**: The dataset's methodology and technical aspects are well-documented, and a disclaimer accompanies its use to inform users of any potential limitations ([FAO GAUL Documentation](https://data.apps.fao.org/catalog/dataset/global-administrative-unit-layers-gaul-2015)).
- **CLC2000**: The EEA provides extensive documentation, including technical guidelines, validation reports, and metadata, detailing the QA processes implemented during the production of the CLC datasets ([CLC2000 Documentation](https://land.copernicus.eu/api/en/products/corine-land-cover/clc-2000)).

## Allocation of Resources

Due to the high computational demands of the project, it was dependent on resource sponsorship. Thanks to the European Space Agency's Network of Resources (ESA NoR), the authors were granted access to their computing cluster, valued at €2,495.00, for a period of five months.

Other than working hours of three authors, no further costs need to be taken into account. 

## Data Security

To ensure data security, the data is stored both locally and in a repository. Additionally, the data is also stored on hardware. Currently, the data is stored in a non-certified repository.

## Ethical Aspects

There are no ethical or legal issues that can have an impact on data sharing.
